<select name="time_secar" style="width: 180px; height: 26px">
<option value="0"></option>
<option value="21">ABC - RN</option>
<option value="39">América - MG</option>
<option value="22">América - RN</option>
<option value="1">Atlético - MG</option>
<option value="2">Atlético - PR</option>
<option value="23">Atlético - GO</option>
<option value="3">Avaí - SC</option>
<option value="24">Bahia - BA</option>
<option value="4">Botafogo - RJ</option>
<option value="25">Central - PE</option>
<option value="27">Brasiliense - DF</option>
<option value="28">Ceará - CE</option>
<option value="5">Corinthians - SP</option>
<option value="6">Coritiba - PR</option>
<option value="38">CRB - AL</option>
<option value="7">Cruzeiro - MG</option>
<option value="30">Figueirense - SC</option>
<option value="8">Flamengo - RJ</option>
<option value="9">Fluminense - RJ</option>
<option value="31">Fortaleza - CE</option>
<option value="10">Goiás - GO</option>
<option value="12">Grêmio - RS</option>
<option value="32">Guarani - SP</option>
<option value="13">Internacional - RS</option>
<option value="34">Juventude - RS</option>
<option value="14">Náutico - PE</option>
<option value="15">Palmeiras - SP</option>
<option value="35">Paraná - PR</option>
<option value="40">Paysandu - PA</option>
<option value="36">Ponte Preta - SP</option>
<option value="37">Portuguesa - SP</option>
<option value="33">Remo - PA</option>
<option value="29">Santa Cruz - PE</option>
<option value="16">Santo André - SP</option>
<option value="17">Santos - SP</option>
<option value="18">São Paulo - SP</option>
<option value="19">Sport - PE</option>
<option value="26">Treze - PB</option>
<option value="11">Vasco - RJ</option>
<option value="20">Vitória - BA</option>
</select>